---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```


<!-- README.md is generated from README.Rmd. Please edit that file -->

# cbsodata4

<!-- badges: start -->

[![CRAN
status](https://www.r-pkg.org/badges/version/cbsodata4)](https://cran.r-project.org/package=cbsodata4)
[![Travis build
status](https://travis-ci.org/statistiekcbs/cbsodata4.svg?branch=master)](https://travis-ci.org/statistiekcbs/cbsodata4)
[![AppVeyor build
status](https://ci.appveyor.com/api/projects/status/github/statistiekcbs/cbsodata4?branch=master&svg=true)](https://ci.appveyor.com/project/edwindj/cbsodata4)

<!-- badges: end -->

The goal of cbsodata4 is allowing access to the Open Data API v4 of Statistics Netherlands.

## Installation

You can install the released version of cbsccb from [CRAN](https://CRAN.R-project.org) with:

<!--
```r
install.packages("cbsodata4")
```
!-->

At the moment only a development version can be installed from
[GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("statistiekcbs/cbsodata4")
```

## Example

```{r}
library(cbsodata4)

# download the set of datasets
datasets <- cbs4_get_datasets()
datasets$Title[1:6]


# filter on Perioden (see meta$PeriodenCodes)
cbs4_get_data("84287NED"
             , Perioden = "2019MM12" # december 2019
             )

# filter on multiple Perioden (see meta$PeriodenCodes)
cbs4_get_data("84287NED"
             , Perioden = c("2019MM12", "2020MM01") # december 2019, january 2020
             )

# to filter on a dimension just add the filter to the query

# filter on Perioden (see meta$PeriodenCodes)
cbs4_get_data("84287NED"
             , Perioden = "2019MM12" # december 2019
             , BedrijfstakkenBranchesSBI2008 = "T001081"
             )


# filter on Perioden with contains
cbs4_get_data("84287NED"
              , Perioden = contains("2020")
              , BedrijfstakkenBranchesSBI2008 = "T001081"
)

# filter on Perioden with multiple contains
cbs4_get_data("84287NED"
              , Perioden = contains(c("2019MM1", "2020"))
              , BedrijfstakkenBranchesSBI2008 = "T001081"
)

# filter on Perioden with contains or = "2019MM12
cbs4_get_data("84287NED"
              , Perioden = contains("2020") | "2019MM12"
              , BedrijfstakkenBranchesSBI2008 = "T001081"
)

# This all works on observations too
cbs4_get_observations( id        = "80784ned"    # table id
                     , Perioden  = "2019JJ00"    # Year 2019
                     , Geslacht  = "1100"        # code for total gender
                     , RegioS    = contains("PV")
                     , Measure   = "M003371_2"
                     )

```

