---
title: "CBS_ccb"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CBS_ccb}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cbsccb)
library(dplyr) # not needed but used for example
```

# Introduction

```{r}
catalogs <- cbs4_get_catalogs() 
catalogs %>% 
  select(Identifier, Title)
```


```{r}
datasets <- cbs4_get_datasets()
datasets %>% 
  select(Identifier, Title) %>% 
  head(2)
```

```{r}
meta <- cbs4_get_metadata("80416ned")
ls.str(meta)
```

```{r}
data <- cbs4_get_observations("80416ned")
data %>% 
  select(-Id, -ValueAttribute) %>% 
  head(5)
```


```{r}
data <- cbs4_get_observations("80416ned")

data %>% 
  select(-Id, -ValueAttribute) %>%
  cbs4_add_labels() %>% 
  head(5) 
```

```{r}
data <- cbs4_get_observations("80416ned")

data %>% 
  select(-Id, -ValueAttribute) %>%
  cbs4_add_date_column() %>% 
  head(5) 

library(tidyr)
data %>% 
  cbs4_add_labels() %>% 
  select(ends_with("Label"), Value) %>% 
  spread(MeasureLabel, Value) %>% 
  head()
```

```{r}
meta <- cbs4_get_metadata("80416ned")
data <- cbs4_get_observations("80416ned")
data %>% 
  select(-Id, -ValueAttribute) %>%
  cbs4_add_unit() %>% 
  head(5) 
```

```{r}
data <- cbs4_get_data("80416ned")
head(data)
```
