---
output: 
  rmarkdown::github_document:
    df_print: kable
vignette: >
  %\VignetteIndexEntry{cbsodata4}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cbsodata4)
```

# Introduction

```{r}
catalogs <- cbs4_get_catalogs() 
catalogs[,1:2]
```


```{r}
datasets <- cbs4_get_datasets()
head(datasets[,c("Identifier", "Title")])
```

```{r}
meta <- cbs4_get_metadata("80416ned")
ls.str(meta)
```

```{r}
obs <- cbs4_get_observations("80416ned")
head(obs)
```


```{r}
obs <- cbs4_get_observations("80416ned")
obs <- cbs4_add_label_columns(obs)
head(obs)
```

```{r}
obs <- cbs4_get_observations("80416ned")
obs <- cbs4_add_date_column(obs)
head(obs)

data <- cbs4_get_data("80416ned")
head(data)
```

```{r}
meta <- cbs4_get_metadata("80416ned")
obs <- cbs4_get_observations("80416ned")
obs <- cbs4_add_unit_column(obs)
head(obs)
```

```{r}
data <- cbs4_get_data("80416ned")
head(data)
```
